name: Deploy to PythonAnywhere

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10' 

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pythonanywhere

    - name: Deploy to PythonAnywhere
      env:
        USERNAME: ${{ secrets.PYTHONANYWHERE_USERNAME }}
        API_TOKEN: ${{ secrets.PYTHONANYWHERE_API_TOKEN }}
        PATH_TO_APP: home/dushr/mysite
        CONSOLE_ID: 36137230
      run: |
        # Create a zip of your app excluding .git
        zip -r flask_app.zip . -x '*.git*'

        # Upload the zip file to PythonAnywhere
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/files/path/$PATH_TO_APP/flask_app.zip" \
          -H "Authorization: Token $API_TOKEN" \
          -F "content=@flask_app.zip"

        # Send commands to the console to unzip and clean up
        curl -X POST "https://www.pythonanywhere.com/api/v0/user/$USERNAME/consoles/$CONSOLE_ID/send_input/" \
          -H "Authorization: Token $API_TOKEN" \
          --data-urlencode "input=cd /$PATH_TO_APP\n"
